services:
  - type: web
    name: logiflow-backend
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm ci && npx prisma generate --schema=./prisma/schema && npx tsx scripts/postgenerate.ts && npx prisma migrate deploy --schema=./prisma/schema && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
      - key: BKASH_BASE_URL
        sync: false
      - key: BKASH_USERNAME
        sync: false
      - key: BKASH_PASSWORD
        sync: false
      - key: BKASH_APP_KEY
        sync: false
      - key: BKASH_APP_SECRET
        sync: false
      - key: BKASH_CALLBACK_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: MAX_DELIVERY_ATTEMPTS
        value: "3"
